# -*- coding: utf-8 -*-
"""mod22_tarefa01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KuH-vbFAyZc1AW3zjyyP3D8KA41QsyPr

# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os monitores
- Divirta-se :)

#### 1. Baixando dados de ativos
    1. Baixe os dados de três ativos da sua escolha do Yahoo Finance, correspondente a um período de pelo menos 2 anos até a data mais recente.
    2. Salve esses dados para que você possa utilizá-los na próxima tarefa.
"""

from pandas_datareader import data as pdr

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
yf.pdr_override()

import datetime as dt
import pandas as pd
import numpy as np

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# start_date = dt.datetime(2019, 1, 1)
# end_date = dt.datetime(2023, 12, 31)
# 
# yf = pdr.get_data_yahoo(['MSFT', 'DIS', 'AAPL'], start=start_date, end=end_date)
# yf.head()

yf.to_csv('dadosLimpos.csv', sep=',')

yf.shape

"""#### 2. Observando a volatilidade dentro do dia
1. Calcule a amplitude de variação do valor do ativo dentro do dia. Essa amplitude você pode calcular com um comando simples de adicionar uma coluna no Pandas: (valor máximo - valor mínimo).
2. Monte um gráfico de linha mostrando a variação dessa amplitude ao longo do período coletado, por ativo.
3. Veja se consegue identificar que ativo apresentou maior volatilidade.
"""

amplitudade = yf['High'] - yf['Low']
amplitudade

amplitudade_v = yf['Adj Close'].stack().reset_index()
amplitudade_v.columns = ['data', 'ativo', 'valor']

amplitudade_v.head()

fig = px.line(amplitudade_v, x='data', y='valor', color='ativo', template='ggplot2')
fig.show()

"""O ativo que apresentou maior volatividade foi o MSFT"""